name: Run Python script hourly

on:
  schedule:
    - cron: '0 * * * *'  # Toutes les heures à minute 0
  workflow_dispatch:  # Permet de déclencher manuellement le workflow

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # Remplacez par la version de Python nécessaire

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create .env file
      run: echo "TODOIST_PERSONAL_TOKEN=${{ secrets.TODOIST_PERSONAL_TOKEN }}" > .env

    - name: Run main.py
      run: python main.py
      env:
        TODOIST_PERSONAL_TOKEN: ${{secrets.TODOIST_PERSONAL_TOKEN}}  # Passe le token en tant que variable d'environnement

    - name: Commit last_run.json
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add configuration.yaml
        git commit -m "Update configuration.yaml [skip ci]"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
