name: Run Python script hourly

on:
  schedule:
    - cron: '0 * * * *'  # Toutes les heures à minute 0
  workflow_dispatch:  # Permet de déclencher manuellement le workflow

jobs:
  run-on-windows:
    runs-on: windows-latest



    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Remplacez par la version de Python nécessaire

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Create .env file
      run: echo "API_TOKEN=${{ secrets.TODOIST_PERSONAL_TOKEN }}" > .env

    - name: Run main.py
      run: python main.py
      env:
        API_TOKEN: ${{ secrets.TODOIST_PERSONAL_TOKEN }}  # Passe le token en tant que variable d'environnement
